name: dart_get_up_to_speed
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  meta: ^1.17.0

# Not packaged with the built app
# Only used during development
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
